### ISSUE TITLE
Planet.java

### ISSUE THREAD

**Issue by MikeMMattinson** [MikeMMattinson/space2d_java_3#1]

**Comment by MikeMMattinson** [comment]
![Image](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/848437ef-db13-4398-a7ab-1d13c7628390)

**Comment by MikeMMattinson** [comment]
package main.java.entity.planets;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Random;

import javax.imageio.ImageIO;

import main.java.GamePanel;
import main.java.entity.Entity;
import main.java.entity.player.Player;
import main.java.utility.Constants;
import main.java.utility.GraphicsUtility;
import main.java.utility.KeyHandler;
import main.java.utility.Vector2d;



/*
 *  + Name: Each planet should have a unique name to identify it within the game.
 *  + Size: This attribute can represent the planet's physical dimensions, such as 
 *      its radius or diameter. In some games, it may affect gameplay or the planet's 
 *      gravitational pull.
 *  + Mass: The mass of a planet can impact its gravitational force and interactions 
 *      with other objects.
 *  + Gravity: Planets can have varying levels of gravity, affecting player movement, 
 *      vehicle handling, and object trajectories.
 *  + Terrain: Define the planet's surface features, including landscapes, mountains, 
 *      valleys, oceans, and more. These attributes can be crucial for exploration and 
 *      gameplay mechanics.
 *  + Climate: Specify the climate or weather conditions on the planet, which can affect 
 *      gameplay, such as temperature extremes, storms, or radiation.
 *  + Atmosphere: Describe the planet's atmosphere, including its composition, pressure, 
 *      and thickness. This can affect breathing and the ability to fly or navigate on the 
 *      planet.
 *  + Temperature: Specify the average and extreme temperatures, which can influence player 
 *      survival and the planet's ecosystem.
 *  + Ecosystem: Create flora and fauna that inhabit the planet, including wildlife, plants, 
 *      and any unique species. These can affect quests, resources, and interactions.
 *  + Resources: Determine what resources are available on the planet, such as minerals, 
 *      energy sources, or rare materials. This can influence resource gathering and crafting 
 *      systems.
 *  + Civilization: Define any intelligent species or civilizations living on the planet, 
 *      including their culture, technology level, and relationship with the player.
 *  + History: Develop a history or backstory for the planet, including significant events, 
 *      ancient ruins, or mysteries that players can discover.
 *  + Quests and Missions: Planetary attributes can be tied to specific quests or missions, 
 *      such as collecting rare resources, exploring ruins, or assisting local inhabitants.
 *  + Visual Appearance: Consider the planet's visual aesthetics, including its colors, 
 *      textures, and skybox, to create an immersive gaming experience.
 *  + Unique Features: If the planet is a central location in the game, it may have unique 
 *      features or anomalies like ancient artifacts, portals, or anomalies that impact gameplay.
 *  + Day-Night Cycle: Implement a day-night cycle to create dynamic lighting conditions and 
 *      atmospheric changes.
 *  + Celestial Events: Include celestial events like meteor showers, eclipses, or planetary rings 
 *      that can enhance the planet's visual appeal.
 *  + Soundscapes: Create ambient sounds or music tracks to complement the planet's atmosphere and 
 *      set the mood.
 * 
 *  generated by chatGPT
 *  Updated 26/Oct/23 Mike
 */

public class Planet extends Entity {
    // Declare variables / attributes
    //int size;
    double mass;
    String color;
    float planetGravity;
    String terrain;
    String climate;
    String atmosphere;
    boolean isDiscovered;
    float planetMinTemperature;
    float planetAveTemperature;
    float planetMaxTemperature;
    String ecosystem;       //these might be classes themselves...
    int resourcesListLength = 20;
    String[] resources = new String[resourcesListLength];
    String civilization;    //these might be classes themselves...
    String history;         //these might be classes themselves...
    String missions;        //these might be classes themselves...
    int uniqueListLength = 20;
    String[] uniqueFeatures = new String[uniqueListLength];
    boolean isDay;      //true = day      false = night
    String planetPath; // path to planet's texture
    GamePanel gp;
    KeyHandler keyH;
    double exploreTimePlayer;
    Parallax pFactor; // parallax factor

    // Define constants for the planet groups and their size ranges
    public static final String[] PLANET_GROUPS = {
        "Terrestrial",
        "Gas Giant",
        "Ice Giant",
        "Hot Jupiter",
        "Super-Earth",
        "Mini-Neptune",
        "Exomoon",
        "Rogue Planet",
        "Habitable Zone"
    };
    
    public static final double[][] SIZE_RANGES = {
        {2000, 8000},  // Terrestrial
        {10000, 50000},  // Gas Giant
        {8000, 30000},  // Ice Giant
        {40000, 100000},  // Hot Jupiter
        {5000, 15000},  // Super-Earth
        {10000, 25000},  // Mini-Neptune
        {1000, 5000},  // Exomoon
        {2000, 10000},  // Rogue Planet
        {3000, 10000}  // Habitable Zone
    };

    // Calculate the mass of the planet
    public double calculateMass() {
        double mass;

        // Find the corresponding index of the planet group
        int groupIndex = -1;
        for (int i = 0; i < PLANET_GROUPS.length; i++) {
            if (planetGroup.equalsIgnoreCase(PLANET_GROUPS[i])) {
                groupIndex = i;
                break;
            }
        }

        if (groupIndex != -1 && groupIndex < SIZE_RANGES.length) {
            // Calculate mass based on size and size range for the given planet group
            double[] sizeRange = SIZE_RANGES[groupIndex];
            mass = planetSize * (sizeRange[0] + sizeRange[1]) / 2.0; // Take the average of the range
        } else {
            // Default mass for unknown planet types
            mass = planetSize * 2000; // Adjust the factor as needed
        }

        return mass;
    }

    //private String name;
    double planetSize; // Size of the planet
    double scaledPlanetSize;
    double distanceFromStar; // Orbital distance from the star
    String planetGroup; // Classification of the planet

    // Generate a random star parallax factor
    private Parallax getRandomStarParallaxFactor() {
        Random random = new Random();
        int parallaxCount = Parallax.values().length;
        int randomIndex = random.nextInt(parallaxCount);
        return Parallax.values()[randomIndex];
    }

    // Generate a random planet group
    private String getRandomPlanetGroup() {
        Random random = new Random();
        int randomIndex = random.nextInt(PLANET_GROUPS.length);
        return PLANET_GROUPS[randomIndex];
    }
    
    public double getExploreTimePlayer() {
        return exploreTimePlayer;
    }

    public void setExploreTimePlayer(double exploreTimePlayer) {
        this.exploreTimePlayer = exploreTimePlayer;
    }

    // Generate a random size for the given planet group
    private double getRandomSizeForGroup(String group) {
        Random random = new Random();
        int groupIndex = -1;
        for (int i = 0; i < PLANET_GROUPS.length; i++) {
            if (PLANET_GROUPS[i].equals(group)) {
                groupIndex = i;
                break;
            }
        }
        
        if (groupIndex != -1) {
            double minSize = SIZE_RANGES[groupIndex][0];
            double maxSize = SIZE_RANGES[groupIndex][1];
            return minSize + (maxSize - minSize) * random.nextDouble();
        }
        
        return 0; // Default size
    }



    // Scale the size using a logarithmic function
    //private static final double INVERSE_LOG_SCALE_FACTOR = .1; 
    private double scaleSize(double originalSize) {
        //return originalSize == 0 ? 0 : Math.log(originalSize + 1) / INVERSE_LOG_SCALE_FACTOR;

        // Define the range of the original size values
        double minOriginalSize = 1000.0;
        double maxOriginalSize = 100000.0;
        
        // Define the range of the scaled size values
        double minScaledSize = 40.0;
        double maxScaledSize = 300.0;
        
        // Use a logarithmic mapping to scale the size
        double scaledSize = minScaledSize + ((Math.log(planetSize) - Math.log(minOriginalSize)) / (Math.log(maxOriginalSize) - Math.log(minOriginalSize)) * (maxScaledSize - minScaledSize));
        
        // Round the scaled size to an integer value
        return (int) Math.round(scaledSize);
    }
    

    public Planet() {
        super();
        this.name += "Planet";
    }
    


    public Planet(Vector2d worldPos, double speed, double heading) {
        super(worldPos, speed, heading);
        this.name += "Planet";
    }

    public Planet(double mass, double planetSize, double scaledPlanetSize, String planetGroup) {
        this.mass = mass;
        this.planetSize = planetSize;
        this.scaledPlanetSize = scaledPlanetSize;
        this.planetGroup = planetGroup;
    }

    public Planet(GamePanel gp, KeyHandler keyH) {
        this.gp = gp;
        this.keyH = keyH;
        this.name += "Planet";
        this.isDiscovered = false;
        this.pFactor  = getRandomStarParallaxFactor();

        // random location in world
        Random random = new Random();

        // random position between +/- half the WORLD
        int halfX = (int) Constants.WORLD_WIDTH / 2;
        int halfY = (int) Constants.WORLD_HEIGHT / 2;
        int x = random.nextInt((int) Constants.WORLD_WIDTH) - halfX;
        int y = random.nextInt((int) Constants.WORLD_HEIGHT) - halfY;
        this.worldPos = new Vector2d(x, y);

        // set planet classification and size
        //this.distanceFromStar = distanceFromStar;
        this.planetGroup = getRandomPlanetGroup();
        this.planetSize = getRandomSizeForGroup(this.planetGroup);
        this.scaledPlanetSize = (int) scaleSize(getRandomSizeForGroup(this.planetGroup));  
        this.mass = calculateMass();
      

        // Convert the random number to a character representing a letter from 'A' to 'Z' in order to use a random planet image
        // maybe change this eventually to select an image based on the planetGroup
        Random letter = new Random();
        int randomNum = letter.nextInt(11);
        char planetLetter = (char) ('A' + randomNum);
        planetPath = String.format("%s.png", planetLetter);
        this.up1 = getPlanetImage(planetPath);
        //this.textureSquare = getPlanetImage("moon.jpg");
        //this.textureCircle = transformSquareToCircle(textureSquare, 400);

        // random speed and heading
        this.speed = 0; //0.05 + random.nextDouble() * 0.05;;
        this.heading = random.nextDouble() * 360;;  
        
        // initialize exploreTimePlayer = 0
        this.exploreTimePlayer = 0;
    }


    public double getScaledPlanetSize() {
        return scaledPlanetSize;
    }

    public void setScaledPlanetSize(double scaledPlanetSize) {
        this.scaledPlanetSize = scaledPlanetSize;
    }

    public double getDistanceFromStar() {
        return distanceFromStar;
    }

    public void setDistanceFromStar(double distanceFromStar) {
        this.distanceFromStar = distanceFromStar;
    }


    public double getPlanetSize() {
        return planetSize;
    }

    public void setPlanetSize(double planetSize) {
        this.planetSize = planetSize;
    }

    public String getPlanetGroup() {
        return planetGroup;
    }

    public void setPlanetGroup(String planetGroup) {
        this.planetGroup = planetGroup;
    }

    // Methods
    public void applyPlanetGravitationalForce(){
        //apply Planet's gravity to object
    }



    public boolean isDiscovered() {
        return isDiscovered;
    }



    public void setDiscovered(boolean isDiscovered) {
        this.isDiscovered = isDiscovered;
    }



    public double getMass() {
        return mass;
    }

    public void setMass(double mass) {
        this.mass = mass;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public float getPlanetGravity() {
        return planetGravity;
    }

    public void setPlanetGravity(float planetGravity) {
        this.planetGravity = planetGravity;
    }

    public String getTerrain() {
        return terrain;
    }

    public void setTerrain(String terrain) {
        this.terrain = terrain;
    }

    public String getClimate() {
        return climate;
    }

    public void setClimate(String climate) {
        this.climate = climate;
    }

    public String getAtmosphere() {
        return atmosphere;
    }

    public void setAtmosphere(String atmosphere) {
        this.atmosphere = atmosphere;
    }

    public float getPlanetMinTemperature() {
        return planetMinTemperature;
    }

    public void setPlanetMinTemperature(float planetMinTemperature) {
        this.planetMinTemperature = planetMinTemperature;
    }

    public float getPlanetAveTemperature() {
        return planetAveTemperature;
    }

    public void setPlanetAveTemperature(float planetAveTemperature) {
        this.planetAveTemperature = planetAveTemperature;
    }

    public float getPlanetMaxTemperature() {
        return planetMaxTemperature;
    }

    public void setPlanetMaxTemperature(float planetMaxTemperature) {
        this.planetMaxTemperature = planetMaxTemperature;
    }

    public String getEcosystem() {
        return ecosystem;
    }

    public void setEcosystem(String ecosystem) {
        this.ecosystem = ecosystem;
    }

    public int getResourcesListLength() {
        return resourcesListLength;
    }

    public void setResourcesListLength(int resourcesListLength) {
        this.resourcesListLength = resourcesListLength;
    }

    public String[] getResources() {
        return resources;
    }

    public void setResources(String[] resources) {
        this.resources = resources;
    }

    public String getCivilization() {
        return civilization;
    }

    public void setCivilization(String civilization) {
        this.civilization = civilization;
    }

    public String getHistory() {
        return history;
    }

    public void setHistory(String history) {
        this.history = history;
    }

    public String getMissions() {
        return missions;
    }

    public void setMissions(String missions) {
        this.missions = missions;
    }

    public int getUniqueListLength() {
        return uniqueListLength;
    }

    public void setUniqueListLength(int uniqueListLength) {
        this.uniqueListLength = uniqueListLength;
    }

    public String[] getUniqueFeatures() {
        return uniqueFeatures;
    }

    public void setUniqueFeatures(String[] uniqueFeatures) {
        this.uniqueFeatures = uniqueFeatures;
    }

    public boolean isDay() {
        return isDay;
    }

    public void setDay(boolean isDay) {
        this.isDay = isDay;
    }

    // define parallax
    /*
     * Author: Mike
     * Created: 3/Nov/23
     */
    public static enum Parallax {
        // Define parallax factos as enum constants
        DISTANT(0.003),
        NEARBY(0.001);
    
        // Add fields to store the parallax factor
        private final double factor;
    
        // Constructor for the enum
        Parallax(double factor) {
            this.factor = factor;
        }
    
        // Getter methods to access the factor
        public double getFactor() {
            return factor;
        }
    
    }

    // Generate toString Method
    @Override
    public String toString(){
        String out = super.toString();
        out += String.format("Mass: %.1f\n", this.mass);
        out += String.format("Size: %.1f\n", this.planetSize);
        out += String.format("Group: %s\n", this.planetGroup);
        out += String.format("Explore time: %.1f\n", this.exploreTimePlayer);
        out += String.format("Parallax: %s\n", this.pFactor);
        return out;
    }

    public BufferedImage getPlanetImage(String planetPath) {
        BufferedImage img;
        img = null;
        try {
            img = ImageIO.read(getClass().getResourceAsStream(planetPath));

        } catch(IOException e) {
            e.printStackTrace();

        }
        return img;

    }



    public void update(Player player) {
        // calculate planet's parallax factor and position
        double playerSpeed = player.getSpeed(); // Get the player's speed
        double playerHeading = player.getHeading(); // Get the player's heading
        double pFactor = this.pFactor.getFactor();

        /*
         *  this is work here that needs to be done
         *  when the player is speeding across sky
         *  after slowing almost to zero and then zero
         *  it appears like the stars are still moving 
         *  and the player is now moving backwards...
         *  we need the speed of stars to slowly come back
         *  to zero as the player is getting back to zero
         * 
         */
        if(playerSpeed < 2){

            speed = playerSpeed * pFactor;

        } else {
            speed = speed + (playerSpeed - speed) * pFactor;
        }
        
        heading = playerHeading - (playerHeading - heading) * pFactor;

        updateWorldPos();
        double distanceToPlayer = distanceTo(player);

        // increment explore time player
        if(distanceToPlayer<=Constants.MIN_DIST_DISCOVER_PLANET){
            this.exploreTimePlayer += .01;
        }

        // update isDiscoverd
        this.isDiscovered = this.exploreTimePlayer > Constants.MIN_TIME_DISCOVER_PLANET;

        // Check if planet has moved outside of the world
        if (GraphicsUtility.isOffWorld(worldPos, 100)) {
            // Calculate the new position on the opposite side of the world
            if (worldPos.getX() < -Constants.WORLD_WIDTH / 2) {
                worldPos.setX(worldPos.getX() + Constants.WORLD_WIDTH);
            } else if (worldPos.getX() > Constants.WORLD_WIDTH / 2) {
                worldPos.setX(worldPos.getX() - Constants.WORLD_WIDTH);
            }

            if (worldPos.getY() < -Constants.WORLD_HEIGHT / 2) {
                worldPos.setY(worldPos.getY() + Constants.WORLD_HEIGHT);
            } else if (worldPos.getY() > Constants.WORLD_HEIGHT / 2) {
                worldPos.setY(worldPos.getY() - Constants.WORLD_HEIGHT);
            }
        }

    }



    public void draw(Graphics2D g2, Player player) { 
        if (true) {
            super.paint(g2);
            BufferedImage image = null;
            image = up1;
            // use graphics utilities to calc screen pos
            Vector2d screenPos = GraphicsUtility.calculateScreenPosition(worldPos, player.getWorldPos());
            int x = (int) screenPos.getX();
            int y = (int) screenPos.getY();
            int m = (int) this.scaledPlanetSize;

            int imageX = x; // X-coordinate of the image
            int imageY = y; // Y-coordinate of the image
            int imageWidth = image.getWidth(); // Width of the image
            int imageHeight = image.getHeight(); // Height of the image
            int discoveryRadius = Constants.MIN_DIST_DISCOVER_PLANET; // Radius of the circle
            
            int screenX = imageX + imageWidth / 2;
            int screenY = imageY - imageHeight / 2;


            g2.setColor(Color.WHITE);
            if(GraphicsUtility.isOnScreen(screenPos, 100)) {
                g2.drawImage(image, screenX-m/2, screenY-m/2, m, m, null);

                // is discovered
                if(isDiscovered) {
                    g2.setColor(Color.GREEN);
                    g2.drawOval(screenX-(m+5)/2, screenY-(m+5)/2, m+5, m+5);
                    this.name = "Unnamed discovered planet";
                }

                // if in closest planets then highlight
                if(player.getClosestPlanets().contains(this)) {
                    drawStringBelow(g2, player, 18  );
                    g2.setColor(Color.BLUE);
                    g2.drawOval(screenX-discoveryRadius/2, screenY-discoveryRadius/2, discoveryRadius, discoveryRadius);
                }

            }
            // highlight if getting close to going off world
            if(GraphicsUtility.isOffWorld(worldPos, 50)) {
                g2.setColor(Color.WHITE);
                g2.drawOval(screenX-discoveryRadius/2, screenY-discoveryRadius/2, 300, 300);

            }

        }
    } 

    public BufferedImage transformSquareToCircle(BufferedImage squareTexture, int planetRadius) {
        int diameter = 2 * planetRadius;
        BufferedImage circularTexture = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
        int centerX = planetRadius;
        int centerY = planetRadius;
        
        for (int x = 0; x < diameter; x++) {
            for (int y = 0; y < diameter; y++) {
                int dx = x - centerX;
                int dy = y - centerY;
                double distance = Math.sqrt(dx * dx + dy * dy);
                
                if (distance < planetRadius) {
                    int sourceX = (int) (dx + centerX);
                    int sourceY = (int) (dy + centerY);
                    int color = squareTexture.getRGB(sourceX, sourceY);
                    circularTexture.setRGB(x, y, color);
                }
            }
        }
        
        return circularTexture;
    }
    

    public static void main(String[] args){
        Planet planet = new Planet(new Vector2d(0,0),0,0);
        planet.setPlanetGroup(planet.getRandomPlanetGroup());
        planet.setPlanetSize(planet.getRandomSizeForGroup(planet.getPlanetGroup()));
        planet.setScaledPlanetSize(planet.getPlanetSize());  
        planet.setMass(planet.calculateMass());
        System.out.println(planet.toString());  // debug console
    }


}

**Comment by nickmattinson** [comment]
I can't tell if you are still having one of the issues mentioned in this thread. If the planets no longer show in the window, you may have unnecessary g2.close(); somewhere in the star / parallax class draw methods.

**Comment by nickmattinson** [comment]
Also, is the "exomoon" (earth looking planet in your screenshot) orbiting the planet?

**Comment by MikeMMattinson** [comment]
How do you like my new little rocket??

**Comment by MikeMMattinson** [comment]
Nothing orbiting yet... each planet is on its own

**Comment by nickmattinson** [comment]
I like the new rocket, I also liked the first one you had made. I like the animations you've got lined up for this rocket too. It will look really good! is the rocket fixed to the center of the screen?

**Comment by MikeMMattinson** [comment]
Yes. Rocket is fixed to the center and there are thrusters when you press on the up button and there is a deceleration image when you push on the down button I don't know if you can see that can you download the code and run it or only when you're in Port on your own computer…

**Comment by nickmattinson** [comment]
no I cannot see the game run at all. I can only see what you do in github and read the code, trying to piece it together in my head.

I can potentially see a very short video that you can send me through messenger of the game running.

**Comment by MikeMMattinson** [comment]
I LOVE YOU, TAKE CARE
