### ISSUE TITLE
Fire bullet. 

### ISSUE THREAD

**Issue by MikeMMattinson** [MikeMMattinson/space2d_java_3#14]
Update the following code segments:
- [x] KeyHandler Key_B
- [x] Constants, if required DURATION, INITIAL_SPEED, MAX_BULLETS_ACTIVE=5
- [x] GamePanel - List<Bullet> bullets
- [x] Player
- [ ] Bullet continues until it hits something or expires.
- [x] Bullet.java
- [x] Bullets.java

**Comment by nickmattinson** [comment]
we have to utilize hit boxes for the bullet and the alien ship. the ryi snow tutorial has a good video explaining how to set up the hit boxes and have them interact with each other.

**Comment by MikeMMattinson** [comment]
![image](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/f134926d-10e7-4d21-992d-7bd75e7f2210)

**Comment by MikeMMattinson** [comment]
![alien_b_58](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/f3af9255-8f1d-4454-bc7e-a14e1884d879)

**Comment by MikeMMattinson** [comment]
```
git fetch origin
git checkout 14-fire-bullet
```

**Comment by MikeMMattinson** [comment]
![image](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/d31dfcb4-6884-46f6-aa39-121abc191ed7)
