### ISSUE TITLE
There is a pixel off in the thrust and decel .png images

### ISSUE THREAD

**Issue by MikeMMattinson** [MikeMMattinson/space2d_java_3#43]

**Comment by nickmattinson** [comment]
git fetch origin
git checkout 43-there-is-a-pixel-off-in-the-thrust-and-decel-png-images

**Comment by MikeMMattinson** [comment]
I believe this is no longer an issue. The new player rocket, named Beta_64.png was redesigned and the pixels are good from one image to the next.
