### ISSUE TITLE
Alien image center.

### ISSUE THREAD

**Issue by MikeMMattinson** [MikeMMattinson/space2d_java_3#84]
Figure out how to put the center of the alien image at the exact world coordinates. You can see the difference between the player image and the alien image by referencing the health and fuel progress bars.
![image](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/38b2016d-24bc-4121-a436-294ca0388484)

**Comment by nickmattinson** [comment]
git fetch origin
git checkout 84-alien-image-center

**Comment by MikeMMattinson** [comment]
i believe this is fixed now, @zmatt01 helped me figure out what was wrong.  There was a sign error in the screenX.
```
            // adjust the alien to be centered
            int screenX = imageX - imageWidth /2 ;
            int screenY = imageY - imageHeight /2;
```
